version: "3.6"
services:

  nginx:
    build: nginx/
    ports:
      - "8080:80"
    links:
      - php

  php:
    build: php/
    privileged: true
    ulimits:
      core: 99999999999
    volumes:
      - ./php:/src
    links:
      - redis-cluster
      - redis0
      - redis1
      - redis2

  redis-cluster:
    image: grokzen/redis-cluster

  redis0:
    image: redis

  redis1:
    image: redis

  redis2:
    image: redis
